on: push

name: Run tests
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DISPLAY: :99
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm ci